server:
  port: 8081

spring:
  jpa:
    show-sql: true
  main:
    allow-bean-definition-overriding: true
  cloud:
    stream:
      bindings:
        input:
          destination: userservice.events
          group: taskservices
      rabbit:
        bindings:
          input:
            consumer:
              autoBindDlq: true

logging:
  level:
    org.hibernate.type.descriptor.sql: trace
