spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/todoplatdb
    username: todoplatdb
    password: todoplatdbpwd
  jpa:
    properties:
      hibernate:
        jdbc:
          lob.non_contextual_creation: true